### ISSUE TITLE
Don't use CSS classes on <body>

### ISSUE THREAD

**Issue by Toflar** [contao/package-manager#1]
As the react needs to render IN some given node, I can ask it to render on `document.body` but cannot adjust the CSS class of `<body>` itself to go for something like `<body class="wide">`.
Can we maybe have something like

```html
<body>
    <div id="app" class="wide">
    <!-- everything goes in here -->
    </div>
</body>
```

? :-)

**Comment by aschempp** [comment]
We currently have a `<div id="content">`. Shall I remap that to `<div id="app">` and apply all classes to that? I assume that also applies to the login and install pages?

**Comment by Toflar** [comment]
There is no `<div id="content">` for the install and login screens. I just need something in general so I'd go for `<div id="app">`. And yes, no CSS classes on `<body>` because I cannot change them without additional, actually redundant, code. :)

**Comment by aschempp** [comment]
Implemented in my mockup. Please adapt and close :)
