### ISSUE TITLE
Buttons should have cursor:pointer

### ISSUE THREAD

**Issue by Toflar** [contao/package-manager#10]
I guess, no? :-)

**Comment by leofeyer** [comment]
Yes.

**Comment by aschempp** [comment]
Well that's against the default browser behavior. Maybe we should not use buttons then but anchors for accessibility. Probably should only use buttons for forms.

**Comment by Toflar** [comment]
I just read up on it and apparently, the pointer is explicitly for links and buttons should never have a pointer cursor. Didn't know this :)

**Comment by leofeyer** [comment]
Don't know what you have read, but it seems that it is common practice to apply `cursor: pointer` to buttons.

* https://wordpress.org/
* https://www.joomla.org/
* https://typo3.org/

And these are just the first three that came into my mind. Even the form here on GitHub has it :)
