### ISSUE TITLE
Composer seems not finding the right php version when using MAMP

### ISSUE THREAD

**Issue by JLBA** [contao/package-manager#3]
Hi everyone,

I got Contao installed in MAMP Pro host with php 5.5.23 in OS X 10.9
Packager suggests me to replace deprecated discordier/httpextendrequest by guzzlehttp//guzzle. But when I try, I got this message : 
 ```
/usr/bin/env php -d memory_limit=1G -d max_execution_time=3000 composer.phar update --no-ansi --no-interaction -v
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for guzzlehttp/guzzle >=6.1.1.0,<6.2-dev -> satisfiable by guzzlehttp/guzzle[6.1.1].
    - guzzlehttp/guzzle 6.1.1 requires php >=5.5.0 -> your PHP version (5.4.45) does not satisfy that requirement.
```
I suppose Composer is verifying MAC OS X version of php instead of MAMP one.

**Comment by aschempp** [comment]
This is not a Contao problem, and the package manager is not yet to be used.

Use Google: https://www.google.ch/search?rls=en&q=mamp+composer ;-)
