### ISSUE TITLE
Use CSS transitions for the taskmanager popup hide and show fade ins/fade outs

### ISSUE THREAD

**Issue by Toflar** [contao/package-manager#8]
I want to get rid of jQuery if possible because we don't really need it and I think it's nicer using transitions anyway for that small gimmick.

**Comment by aschempp** [comment]
I've added the CSS animation and state handling for console. We also need to toggle classes on the app content, not sure how the console should do that?

**Comment by Toflar** [comment]
Register to the `displayTaskPopup` and `hideTaskPopup` events. Can you do that? Or tell me where the classes have to be set and what the names are? :D

**Comment by aschempp** [comment]
The classes are `blur-in` and `blur-out` on `#content`

**Comment by Toflar** [comment]
Implemented in https://github.com/contao/package-manager/commit/c6e925a1070d7b58cd8b0decd3ef7d4f8bffb388
